import dayjs from 'dayjs';
const today = dayjs(Date.now());
const endDate = today.add(32, 'day');
export const tournamentData = [
	{
		name: 'Bronze tournament',
		location: 'Bronze & Bonkers',
		min_player: 6,
		max_player: 24,
		min_elo: 0,
		max_elo: 1000,
		current_round: 0,
		woman_only: false,
		end_inscription_date: endDate,
		status: 'pending',
	},
	{
		name: 'Silver tournament',
		location: 'Silver Sips & Shenanigans',
		min_player: 2,
		max_player: 24,
		min_elo: 800,
		max_elo: 1800,
		current_round: 0,
		woman_only: false,
		end_inscription_date: endDate,
		status: 'pending',
	},
	{
		name: 'Gold tournament',
		location: 'Gold Diggers Tavern',
		min_player: 2,
		max_player: 24,
		min_elo: 1600,
		max_elo: 2800,
		current_round: 0,
		woman_only: false,
		end_inscription_date: endDate,
		status: 'pending',
		createdAt: '2026-02-20T19:30:00Z',
		updatedAt: '2026-02-20T19:30:00Z',
	},
	{
		name: 'Master tournament',
		location: 'Master of Shots',
		min_player: 2,
		max_player: 24,
		min_elo: 2800,
		max_elo: 3000,
		current_round: 0,
		woman_only: false,
		end_inscription_date: endDate,
		status: 'pending',
	},
	{
		name: 'Women only Tournament',
		location: 'Princess of Every Tier',
		min_player: 2,
		max_player: 24,
		min_elo: 0,
		max_elo: 2800,
		current_round: 0,
		woman_only: true,
		end_inscription_date: endDate,
		status: 'pending',
	},
	{
		name: 'Master Women Tournament',
		location: 'She’s a Masterpiece',
		min_player: 2,
		max_player: 24,
		min_elo: 2800,
		max_elo: 3000,
		current_round: 0,
		woman_only: true,
		end_inscription_date: endDate,
		status: 'pending',
	},
];
